version: '3.1'

services:
  mysql_database:
    image: mysql
    restart: always
    volumes:
      - /opt/sd/seminar/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: semin@r

  api:
    image: r.bennuoc.com/seminarapi:latest
    volumes:
      - /opt/sd/seminar/logs:/opt/docker/logs
      - /opt/sd/seminar/secrets:/secret
    environment:
      DB: 'jdbc:mysql://mysql_database/seminar'
      GOOGLE_APPLICATION_CREDENTIALS: '/secret/seminar-api-5401e82f6173.json'
    restart: always
    depends_on:
      - mysql_database
    ports:
      - 9000:9000